### ISSUE TITLE
IllegalStateException: FragmentManager is already executing transactions

### ISSUE THREAD

**Issue by Zhuinden** [Zhuinden/simple-stack-extensions#4]
```
    java.lang.IllegalStateException: FragmentManager is already executing transactions
        at androidx.fragment.app.FragmentManager.ensureExecReady(FragmentManager.java:1790)
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1855)
        at androidx.fragment.app.FragmentManager.executePendingTransactions(FragmentManager.java:489)
        at com.zhuinden.simplestackextensions.fragments.DefaultFragmentStateChanger.handleStateChange(DefaultFragmentStateChanger.java:100)
```

`executePendingTransactions` is called specifically to ensure that the FragmentManager is not out of date, however it appears that calling navigation methods directly from `onViewCreated` can make it explode.

This seems to be somewhat new behavior, technically I ~~should probably just consume it (check if fragment manager is executing transactions right now, and if yes, then skip the sanity check.)~~

Temporary workaround is `handler.post {`.

The minor pain point is that theoretically, `StateChanger` would allow for asynchronous state changes, but the intended usage is with `SimpleStateChanger`, which means I don't have the `CompletionCallback`, and I don't want to break API for this... I'll think about the effects of adding the delay to the DefaultFragmentStateChanger.

**Comment by Zhuinden** [comment]
Fixed in https://github.com/Zhuinden/simple-stack-extensions/commit/7ffba2e9a6e492385fdcd338c8d9c4c5b87efb14

**Comment by Zhuinden** [comment]
Objectively, this would require making the StateChanger async, but that would break the currently existing APIs. 

So I will assume that people will already initialize their lazy lookups before triggering these navigation events. :/

Nonetheless, theoretically it should work.
